# Generated by Django 5.1.4 on 2024-12-19 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='Nacionalidad')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('fecha_na', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
            options={
                'db_table': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('genero', models.CharField(max_length=50, verbose_name='Genero')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
                ('fecha_pu', models.DateField(verbose_name='Fecha de publicacion')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.autor')),
            ],
            options={
                'db_table': 'libros',
            },
        ),
    ]
